#!/usr/bin/env bash

# Source files for implantation into new ISO (ks.cfg, etc.)
# This needs to be an absolute path, not a relative path.
# Also serves as the base for all relative paths defined below.
# Default is pwd 
#SRCDIR=""

# Source Media ISO Location
# ISOSRCDIR=""

# OEM Source Media File Name
OEMSRCISO="rhel-8.10-x86_64-dvd.iso"

# Create new full boot ISO
CREATEBOOTISO="true"

# Insert ks.cfg in boot ISO (Cases where second OEMDRV ISO may not be an option)
KSINBOOTISO="true"
#KSINBOOTISO="false"

## New ISO file suffix. Adds suffix to iso name. Ex: isoname_suffix.iso
# Randomly generate a string for serialization
# Combine suffixes with date in YYYY-MM-DD format
ADDSUFFIX="true"

# Kickstart file location passed to bootloader when KSINBOOTISO is set
# Default is on the ISO file, but could be a network location
KSLOCATION="hd:LABEL=RHEL-8-9-0-BaseOS-x86_64:\/ks.cfg"

# Create OEMDRV volume ISO
#CREATEOEMDRVISO="true"

# FIPS Mode
ENABLEFIPS="true"

# Write plaintext passwords to files
# Generally uneeded, but useful for console testing.
# NOT Recommended to write plaintext passwords out.
WRITEPASSWDS="true"

WRITESSHKEYS="false"

# Root password - Specify a password in plain text.
# Generally uneeded, but useful for console testing.
# NOT Recommended to write plaintext passwords out.
#password=""


##OS Type version
# Set default OS. (Options: "RHEL" or "CentOS")
OSTYPE="RHEL" 
#RHEL OS major version. (Options: "8" or "9")
MAJOROSVERSION="8"
# #RHEL OS minor version. (Options: "See RHEL web for minor versions. Default is 9")
# MINOROSVERSION="9"

#######################
# Kickstart Variables #
#######################

# Service admin account for ansible
username_01="csansi"
#username_01_gecos:=Ansible Service Account
#password_username_03='changeme'

# Service admin account for nessus
username_02="csacas"
username_02_gecos="Nessus Admin Account"
#password_username_03='changeme'

# Custom admin account
username_03="csadmin"
username_03_gecos="Regular Admin Account"
password_username_03='changeme'

## Enable drive encryption by LUKS
ENABLELUKS="true"

## Offline Repo changes.
# Enable offline repo
ISOFFLINEREPO="false" # Default is "false"

## Offline repo location
# OFFLINEREPO='http://repo8/configs/offline_redhat8.repo' #Default if not defined

# NOTE: Timezone names are sourced from the python pytz.all_timezones list
TIMEZONE="Etc/UTC"

# Change this setting to the local NTP server. Comma delimited.
NTP_SERVERS=""

## Logical volume sizes. NO COMMAS!!!
# / filesystem logical volume size
#LOGVOLSIZEROOT="40960"
LOGVOLSIZEROOT="51200"
# /home filesystem logical volume size
#LOGVOLSIZEHOME="18332"
LOGVOLSIZEHOME="40960"

# Applies DISA-STIG for RHEL8/9. See https://static.open-scap.org/ssg-guides/ssg-rhel8-guide-stig.html or https://static.open-scap.org/ssg-guides/ssg-rhel9-guide-stig.html
APPLYOPENSCAPSTIG="true"

## Enable to set virtualization options on the VM. !!Only enable on bare metal installs.!! Not tested in VM environments.
# ISVIRTUALPLATFORM="true"
# PCIPASSTHROUGH="true"
# INTELCPU="true"
ISVIRTUALPLATFORM="false" # Default is "false"
PCIPASSTHROUGH="false" # Default is "false"
INTELCPU="false" # Default is "false"

# Enable serial console display
SERIALDISPLAY="true" # Default is "false"